repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    default_install_hooks_types: [pre-push]
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  default_install_hooks_types: [pre-push]
  rev: v0.0.285
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
